language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
script:
    - python scripts/manager.py initdb
    - tox
    - nosetests -v --with-coverage --cover-package=prony
notifications:
    email:
        recipients:
            - promisejohn@qq.com
        on_success: always
        on_failure: always

branches:
    only:
        - master
        - develop

after_success:
    - coveralls
